In [59]:
df = {
    'Color': ['red', 'red', 'red','yellow','yellow','yellow','yellow', 'yellow', 'yellow','red'],
    'Type': ['sports','sports','sports','sports','sports','SUV','SUV','SUV','SUV','sports'],
    'Origin': ['domestic','domestic','domestic','domestic','imported','imported','imported','domestic','imported','domestic'],
    'Stolen': ['yes','no', 'yes','no', 'yes','no','yes', 'no', 'no','yes']
}

In [62]:
df = pd.DataFrame(df)
df

Color    Type    Origin Stolen
0     red  sports  domestic    yes
1     red  sports  domestic     no
2     red  sports  domestic    yes
3  yellow  sports  domestic     no
4  yellow  sports  imported    yes
5  yellow     SUV  imported     no
6  yellow     SUV  imported    yes
7  yellow     SUV  domestic     no
8  yellow     SUV  imported     no
9     red  sports  domestic    yes

In [64]:
Color=preprocessing.LabelEncoder().fit_transform(df.loc[:,'Color'])
Type=preprocessing.LabelEncoder().fit_transform(df.loc[:,'Type'])
Origin=preprocessing.LabelEncoder().fit_transform(df.loc[:,'Origin'])
Stolen = preprocessing.LabelEncoder().fit_transform(df.loc[:,'Stolen'])
x = Color.reshape(-1,1)
y = Stolen

In [63]:
print("\n\n",Color, "\n\n",Type,"\n\n",Origin,"\n\n",Stolen,"\n\n")



 [0 0 0 1 1 1 1 1 1 0] 

 [1 1 1 1 1 0 0 0 0 1] 

 [0 0 0 0 1 1 1 0 1 0] 

 [1 0 1 0 1 0 1 0 0 1] 




In [67]:
model = GaussianNB().fit(x,y)
a = input("Choose color : Red:0 or Yellow:1)  = ")
b = input("Type : Sports:1 or SUV:0  = ")
c = input("Origin: Domestic:0 or Imported:1  =  ")

#Store the output in the y_pred :
y_pred = model.predict([[int(a),int(b),int(c)]])

#for_loop to predict customisable output
if y_pred ==[1]:
    print("\n\n Answer : Chances of being Stolen is high \n\n")
else: 
    print("\n\nAnswer : Won't be Stolen, Car is not safe \n\n")

Choose color : Red:0 or Yellow:1)  =  0
Type : Sports:1 or SUV:0  =  0
Origin: Domestic:0 or Imported:1  =   0




 Answer : Chances of being Stolen is high 


